<?php

if (!isset($configdeclared)) {
$configdeclared=1;

/* date in the past */
// header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
/* always modified */
// header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
/* HTTP/1.1 */
// header("Cache-Control: no-cache, must-revalidate");
/* HTTP/1.0 */
// header("Pragma: no-cache");

$urlhost = "forum.donutzracing.com";
$furlroot = "/forum";
$urlroot = $furlroot . "/m";
}
?>
