<?php
/* MySQL account info */
$sql_username = "forums";
$sql_password = "Hugnewm0";
$sql_host = "localhost";
$database = "kawf";


$create_key = "9Schiaty";

$bounce_host = "curtis.curtisfong.org";

/* note that $cookie_host can also be an array to guarantee cookies are stored
 * for several domains at once: */
/* $cookie_host = array(".kawf.org",".kawf.net"); */
$cookie_host = array(".wayot.org",".wayot.net");
?>
